source ${ZDOTDIR}/config/cache.zsh
source ${ZDOTDIR}/config/history.zsh
source ${ZDOTDIR}/config/aliases.zsh
source ${ZDOTDIR}/config/completions.zsh
source ${ZDOTDIR}/config/functions.zsh
source ${ZDOTDIR}/config/integrations.zsh

# Source the static plugin file generated by antidote.
# To update plugins: antidote load < ${ZDOTDIR}/zsh_plugins.txt > ${ZDOTDIR}/zsh_plugins.zsh
source ${ZDOTDIR}/zsh_plugins.zsh
