#!/bin/bash
# Removes symlinks created by stow.

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT=$(dirname "$SCRIPT_DIR")
OS=$(uname -s)

echo "🧹 Removing config symlinks..."
stow -d "$PROJECT_ROOT" -t "$HOME/.config" -D config

if [[ "$OS" == "Darwin" ]]; then
  stow -d "$PROJECT_ROOT" -t "$HOME/.config" -D darwin
else
  stow -d "$PROJECT_ROOT" -t "$HOME/.config" -D linux
fi

echo "🧹 Removing home symlinks..."
stow -d "$PROJECT_ROOT" -t "$HOME" -D home

echo "✅ Clean complete."
