#!/bin/bash
# Removes symlinks created by stow.

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT=$(dirname "$SCRIPT_DIR")

echo "🧹 Removing config symlinks..."
stow -d "$PROJECT_ROOT" -t "$HOME/.config" -D config

echo "🧹 Removing home symlinks..."
stow -d "$PROJECT_ROOT" -t "$HOME" -D home

echo "✅ Clean complete."
