"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character\
"""

right_format = """
$status\
$cmd_duration\
$python\
$conda\
$terraform\
$gcloud
"""

[gcloud]
disabled = true
format = 'on [$symbol$account]($style) '

[git_branch]
format = "$branch "

[package]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "🐍"
version_format = "${raw}"

[terraform]
format = '[$symbol$workspace]($style) '
